/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Christian' at '5/13/17 8:09 PM' with Gradle 2.9
 *
 * @author Christian, @date 5/13/17 8:09 PM
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
